[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings= ["@uniswap=lib",
"@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/", 
"@openzeppelin=lib/openzeppelin-contracts", 
"@zkFi=lib/v1-protocol"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
